FROM node:stretch
#FROM node:alpine

RUN apt-get update && apt-get install -y \
  supervisor \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV TZ=America/Argentina/Buenos_Aires
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#COPY docker/pip.conf /etc/
#COPY docker/entrypoint.sh /
#COPY docker/supervisor/flask.conf /etc/supervisor/conf.d
COPY src /src
#RUN cd /src && pip3 install --trusted-host pypi.econo.unlp.edu.ar --upgrade -e .
#RUN cd /src && npm install @angular/cli

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/src/node_modules/.bin/

#WORKDIR /src

#EXPOSE 5000

#ENTRYPOINT ["/entrypoint.sh"]
